# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
stages:
  - build
  - run

first-job:
  # Define stage
  stage: build
  # What to run on the job.
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

second-job:
  stage: run
  script:
    - npm start
  artifacts:
    paths:
      - node_modules/
