image: node:lts


stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cd website
    - npm install
    - npm run build

pages:
  stage: deploy
  script:
    - cd website
    - npm install
    - npm run build
    - mv ./build ../public
  artifacts:
    paths:
      - public
  only:
    - main